- hosts: localhost
  become: yes
  tasks:
   - name: Install Git
     yum: name=git state=present
   - name: git clone
     git:
      repo: 'https://github.com/mukund-p/Login_Web_App.git'
      dest: /home/ansible/maven-web-app
